version: '3.8'

services:
  pgdb:
    container_name: pgdb_scrapping
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: scrapping
      POSTGRES_USER: articles
      POSTGRES_PASSWORD: articles
    volumes:
      - ./docker_init.sql:/docker-entrypoint-initdb.d/docker_init.sql
#      - pg-data:/data/db

volumes:
  mongo-data: