scraping:
  host: :9003
  old_article: 23847623

database:
  dialect: pgx
  dsn: "host=127.0.0.1 port=5432 user=articles password=articles dbname=scrapping sslmode=disable"
  maxOpenConns: 10
  maxIdleConns: 5
  connMaxLifeTime: 3600